name: 归零者
on:
    schedule:
        - cron: "30 20 * * *"
    workflow_dispatch:
permissions:
    contents: read
jobs:
    zero-homers:
        environment: MoegirlPedia
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # main
              with:
                  egress-policy: audit
            - name: 准备 Socket Firewall
              uses: socketdev/action@ba6de6cc0565af1f42295590380973573297e31f # main
              with:
                  mode: firewall
            - name: 签出
              uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # main
            - name: 准备 node.js
              uses: actions/setup-node@0355742c943ddb13ca8a6b700f824231caa91e75 # main
              with:
                  node-version: 20
                  check-latest: true
            - name: 准备 pnpm
              uses: step-security/action-setup@0ad50dc56a23060fa78b14cfcf0677c4e14b42bc # main
              with:
                  version: 10
                  cache: true
            - name: 安装 pnpm 依赖
              run: sfw pnpm install --prod
            - name: 准备 Tailscale
              uses: tailscale/github-action@06afa10de8c4789722e373354c62fd95815b31ad # main
              with:
                  oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
                  oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
                  tags: tag:ci
                  version: latest
            - name: 运行归零者-zh
              env:
                  MOEGIRL_ZH_BOTUSERNAME: ${{ vars.MOEGIRL_ZH_BOTUSERNAME }}
                  MOEGIRL_ZH_BOTPASSWORD: ${{ secrets.MOEGIRL_ZH_BOTPASSWORD }}
                  MOEGIRL_MOEGIRLSSOUSERID: ${{ vars.MOEGIRL_MOEGIRLSSOUSERID }}
                  MOEGIRL_MOEGIRLSSOTOKEN: ${{ secrets.MOEGIRL_MOEGIRLSSOTOKEN }}
                  OTEL_TRACES_EXPORTER: ${{ vars.OTEL_TRACES_EXPORTER }}
                  OTEL_EXPORTER_OTLP_ENDPOINT: ${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}
                  OTEL_EXPORTER_OTLP_INSECURE: ${{ vars.OTEL_EXPORTER_OTLP_INSECURE }}
                  OTEL_NODE_RESOURCE_DETECTORS: ${{ vars.OTEL_NODE_RESOURCE_DETECTORS }}
                  OTEL_SERVICE_NAME: ${{ vars.OTEL_SERVICE_NAME }}
              run: node -r ./logger.js 归零者-zh
            - name: 运行归零者-cm
              if: always()
              env:
                  MOEGIRL_CM_BOTUSERNAME: ${{ vars.MOEGIRL_CM_BOTUSERNAME }}
                  MOEGIRL_CM_BOTPASSWORD: ${{ secrets.MOEGIRL_CM_BOTPASSWORD }}
                  MOEGIRL_MOEGIRLSSOUSERID: ${{ vars.MOEGIRL_MOEGIRLSSOUSERID }}
                  MOEGIRL_MOEGIRLSSOTOKEN: ${{ secrets.MOEGIRL_MOEGIRLSSOTOKEN }}
                  OTEL_TRACES_EXPORTER: ${{ vars.OTEL_TRACES_EXPORTER }}
                  OTEL_EXPORTER_OTLP_ENDPOINT: ${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}
                  OTEL_EXPORTER_OTLP_INSECURE: ${{ vars.OTEL_EXPORTER_OTLP_INSECURE }}
                  OTEL_NODE_RESOURCE_DETECTORS: ${{ vars.OTEL_NODE_RESOURCE_DETECTORS }}
                  OTEL_SERVICE_NAME: ${{ vars.OTEL_SERVICE_NAME }}
              run: node -r ./logger.js 归零者-cm
            - name: 运行归零者-en
              if: always()
              env:
                  MOEGIRL_EN_BOTUSERNAME: ${{ vars.MOEGIRL_EN_BOTUSERNAME }}
                  MOEGIRL_EN_BOTPASSWORD: ${{ secrets.MOEGIRL_EN_BOTPASSWORD }}
                  MOEGIRL_MOEGIRLSSOUSERID: ${{ vars.MOEGIRL_MOEGIRLSSOUSERID }}
                  MOEGIRL_MOEGIRLSSOTOKEN: ${{ secrets.MOEGIRL_MOEGIRLSSOTOKEN }}
                  OTEL_TRACES_EXPORTER: ${{ vars.OTEL_TRACES_EXPORTER }}
                  OTEL_EXPORTER_OTLP_ENDPOINT: ${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}
                  OTEL_EXPORTER_OTLP_INSECURE: ${{ vars.OTEL_EXPORTER_OTLP_INSECURE }}
                  OTEL_NODE_RESOURCE_DETECTORS: ${{ vars.OTEL_NODE_RESOURCE_DETECTORS }}
                  OTEL_SERVICE_NAME: ${{ vars.OTEL_SERVICE_NAME }}
              run: node -r ./logger.js 归零者-en
            - name: 运行归零者-ja
              if: always()
              env:
                  MOEGIRL_JA_BOTUSERNAME: ${{ vars.MOEGIRL_JA_BOTUSERNAME }}
                  MOEGIRL_JA_BOTPASSWORD: ${{ secrets.MOEGIRL_JA_BOTPASSWORD }}
                  MOEGIRL_MOEGIRLSSOUSERID: ${{ vars.MOEGIRL_MOEGIRLSSOUSERID }}
                  MOEGIRL_MOEGIRLSSOTOKEN: ${{ secrets.MOEGIRL_MOEGIRLSSOTOKEN }}
                  OTEL_TRACES_EXPORTER: ${{ vars.OTEL_TRACES_EXPORTER }}
                  OTEL_EXPORTER_OTLP_ENDPOINT: ${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}
                  OTEL_EXPORTER_OTLP_INSECURE: ${{ vars.OTEL_EXPORTER_OTLP_INSECURE }}
                  OTEL_NODE_RESOURCE_DETECTORS: ${{ vars.OTEL_NODE_RESOURCE_DETECTORS }}
                  OTEL_SERVICE_NAME: ${{ vars.OTEL_SERVICE_NAME }}
              run: node -r ./logger.js 归零者-ja
            - name: 运行归零者-library
              if: always()
              env:
                  MOEGIRL_LIBRARY_BOTUSERNAME: ${{ vars.MOEGIRL_LIBRARY_BOTUSERNAME }}
                  MOEGIRL_LIBRARY_BOTPASSWORD: ${{ secrets.MOEGIRL_LIBRARY_BOTPASSWORD }}
                  MOEGIRL_MOEGIRLSSOUSERID: ${{ vars.MOEGIRL_MOEGIRLSSOUSERID }}
                  MOEGIRL_MOEGIRLSSOTOKEN: ${{ secrets.MOEGIRL_MOEGIRLSSOTOKEN }}
                  OTEL_TRACES_EXPORTER: ${{ vars.OTEL_TRACES_EXPORTER }}
                  OTEL_EXPORTER_OTLP_ENDPOINT: ${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}
                  OTEL_EXPORTER_OTLP_INSECURE: ${{ vars.OTEL_EXPORTER_OTLP_INSECURE }}
                  OTEL_NODE_RESOURCE_DETECTORS: ${{ vars.OTEL_NODE_RESOURCE_DETECTORS }}
                  OTEL_SERVICE_NAME: ${{ vars.OTEL_SERVICE_NAME }}
              run: node -r ./logger.js 归零者-library
            - name: keep
              if: always()
              run: true
